apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbuCloud1/EKS-GameApp-Project.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: 2048-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
